### ISSUE TITLE
Figure out and document how to properly configure MPI.jl etc.

### ISSUE THREAD

**Issue by sloede** [trixi-framework/libtrixi#10]
@bgeihe had some issues with coupling MESSy to Trixi.jl that seem to be due to mismatching MPI libraries/p4est libraries. We should figure out how to do this properly and then document it for the users (and us!).

**Comment by bgeihe** [comment]
See also #12

**Comment by sloede** [comment]
@bgeihe Can this be closed as well?

**Comment by bgeihe** [comment]
Documentation is still missing. E.g. for switching to system MPI and p4est. I will do this.

**Comment by bgeihe** [comment]
However, it currently does not work on my laptop. When I execute `libtrixi-init-julia` I end up with

```
Precompiling project...
  ✗ P4est
  ✗ Trixi
  ✗ LibTrixi
  187 dependencies successfully precompiled in 443 seconds. 1 already precompiled.
  3 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages


SUCCESS: Julia has been set up for libtrixi! 🐳
```

It works when I first add everything to julia and change to system MPI afterwards. Also I needed to set system libraries of `p4est` and `sc`, like

```
libp4est = "/home/p4est/lib/libp4est.so"
libsc = "/home/p4est/lib/libsc.so"
```

Is this similar for you. Or is my setup somehow borked?

**Comment by sloede** [comment]
> Is this similar for you. Or is my setup somehow borked?

No, I guess for adding Trixi.jl and p4est there is (much) more to do than for our dummy setup 😅 It's annoying though that the return code of Julia is apparently indicating success even though precompilation failed. I think you just need to tinker with it a little bit and go step by step. Also, if you need to first install everything and then switch out the libraries, that's fine as well - just figure out what works for you and then finally put everything into the init script 🐳

**Comment by bgeihe** [comment]
For me it works with #24

**Comment by sloede** [comment]
OK, then let's close this in favor of #26?
