### ISSUE TITLE
Current main requires julia 1.9

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#119]
I overlooked that the filter expressions 
https://github.com/trixi-framework/libtrixi/blob/50c60c997439a516da0e3f1e8d4786d3b5443c43/LibTrixi.jl/src/LibTrixi.jl#L67
require julia 1.9 at least. 

One could rewrite this (non-critical) piece of code or bump the the compat entry.

**Comment by sloede** [comment]
If (trivially) possible, I'd try to continue to support Julia v1.8 for now. It's just the filter expression that does not work, right? Something like
```julia
filter(p -> p.name == "whatever", Pkg.dependencies() |> values |> collect)
```
should still work
