### ISSUE TITLE
Co-existence of MPI.jl in libtrixi and MPI in external application

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#12]
In case an external application initializes `MPI` and then initializes `libtrixi`, which internally initializes `MPI.jl`, I see the following crash:

```
[14244] signal (11.1): Segmentation fault
in expression starting at none:1
MPI_Comm_size at /usr/lib/libmpi.so.40 (unknown line)
MPI_Comm_size at /home/bene/.julia/dev/MPI/src/api/generated_api.jl:999 [inlined]
Comm_size at /home/bene/.julia/dev/MPI/src/comm.jl:79
unknown function (ip: 0x7f86c3d06442)
_jl_invoke at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-9/src/gf.c:2758 [inlined]
ijl_apply_generic at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-9/src/gf.c:2940
jl_apply at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-9/src/julia.h:1879 [inlined]
do_call at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-9/src/interpreter.c:126
eval_value at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-9/src/interpreter.c:226
eval_stmt_value at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-9/src/interpreter.c:177 [inlined]
eval_body at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-9/src/interpreter.c:624
jl_interpret_toplevel_thunk at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-9/src/interpreter.c:762
jl_toplevel_eval_flex at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-9/src/toplevel.c:912
jl_toplevel_eval_flex at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-9/src/toplevel.c:856
ijl_toplevel_eval_in at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-9/src/toplevel.c:971
ijl_eval_string at /cache/build/default-amdci4-6/julialang/julia-release-1-dot-9/src/jlapi.c:113
trixi_initialize at /home/bene/UniKoeln/libtrixi/src/trixi.c:58
main at /home/bene/UniKoeln/libtrixi/examples/messy_mockup.c:45
unknown function (ip: 0x7f86e6dd784f)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
_start at ./messy_mockup (unknown line)
Allocations: 618896 (Pool: 617990; Big: 906); GC: 1
Segmentation fault (core dumped)
```

Indeed, the `comm` object on the julia side has lots of `0x0` pointers in this situation. 

In case `MPI` is initialized via the C-API from within libtrixi, everything works as expected.

A more or less minimal example can be found in branch
https://github.com/trixi-framework/libtrixi/tree/embedding_julia_with_mpi

Interestingly enough, something similar works with Python:
https://github.com/trixi-framework/libtrixi/tree/embedding_python_with_mpi

**Comment by sloede** [comment]
Can you maybe lost exactly which steps I'd have to take to reproduce this error on Roci?

**Comment by bgeihe** [comment]
```
git clone git@github.com:trixi-framework/libtrixi.git
git switch embedding_julia_with_mpi
cd run_julia_MPIonly
julia --project=. -e "using Pkg; Pkg.instantiate()"    # not sure
cd ..
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=debug  ..
make
cd examples
./messy_mockup
```

**Comment by sloede** [comment]
Sorry, cannot (fully) reproduce:
```
mschlott@pcm016:~/hackathon/libtrixi/build> examples/messy_mockup

Setting up MPI from calling C executable...
MPI Initialized: return 0, init 0
MPI_Init: return 0, threadlevel requested 2, provided 2
MPI rank: return 0, rank 0
MPI size: return 0, size 1

Setting up MPI from C library...
MPI Initialized: return 0, initialized 1
MPI rank: return 0, rank 0
MPI size: return 0, size 1

  Activating new project at `/mnt/ssd/home/mschlott/hackathon/run_julia_MPIonly`

Checking MPI from Julia...
```
From the code I see that much more should be happening, but for some reason I do not get the errors...

**Comment by sloede** [comment]
Ah, now it works in that it fails 😅. It is crucial to be in the correct folder (i.e., running it from the `build` dir does _not_ work)

**Comment by sloede** [comment]
For me, the `MPI_COMM_WORLD` pointer on the Julia side is not `NULL` though:
```
[snip]
COMM_WORLD: MPI.Comm(Ptr{Nothing} @0x00007f1ff4ad93e0)
[snip]
```

**Comment by sloede** [comment]
But this is actually the problem, I think:

Whenever I run `messy_mockup`, the pointer values differ between C and Julia. On the C side, it consistently reports something like
```
0x55d8244f8020
0x55d75108c020
0x557d45147020
```
while on the Julia side, it consistently reports
```
0x00007fe480b5b3e0
0x00007f15f43b63e0
0x00007fef4e4913e0
```

Thus it seems like the MPI objects on the Julia do not get proper values upon initialization. If I fix this by passing the pointer from C to Julia, it seems to to work again (see https://github.com/trixi-framework/libtrixi/commit/f5e8f58b19913b1ac829238e016f225e7a01b743 for the relevant changes):
```
Setting up MPI from calling C executable...
[EXT] MPI Initialized: return 0, initialized 0, MPI_COMM_WORLD 0x5580153cb020
[EXT] MPI_Init: return 0, threadlevel requested 2, provided 2
[EXT] MPI rank: return 0, rank 0
[EXT] MPI size: return 0, size 1

Setting up MPI from C library...
[INT] MPI Initialized: return 0, initialized 1, MPI_COMM_WORLD 0x5580153cb020
[INT] MPI rank: return 0, rank 0
[INT] MPI size: return 0, size 1

  Activating project at `/mnt/ssd/home/mschlott/hackathon/libtrixi/run_julia_MPIonly`

Checking MPI from Julia...

Initialized: true
MPI_COMM_WORLD: MPI.Comm(Ptr{Nothing} @0x00007f9178f143e0)
MPI_COMM_WORLD_C: MPI.Comm(Ptr{Nothing} @0x00005580153cb020)
MPI.jl: rank: 0
MPI.jl: size: 1
```

**Comment by sloede** [comment]
Fixed by https://github.com/trixi-framework/libtrixi/commit/4d311fdf0e4d4881fb499ca2c32899327c8fd2b6. Now it should work again with the current version of the [embedding_julia_with_mpi](https://github.com/trixi-framework/libtrixi/tree/embedding_julia_with_mpi) branch. If it does not, please let me know.

**Comment by sloede** [comment]
@bgeihe With https://github.com/trixi-framework/libtrixi/commit/c8a9268461b92667d937bbaab2793e255b705bea having been pushed to `main` (without a PR 😱), can this issue be closed?

**Comment by bgeihe** [comment]
:flushed: Shame on me.
Strange though, don't we have the main branch protected? At least my client reported something like this, when I accidentally tried to push. Obviously it worked nonetheless.

Yes, this can be closed now.

Thanks again for solving this!
