### ISSUE TITLE
Allow using local shared libraries instead of Julia-shipped one

### ISSUE THREAD

**Issue by sloede** [trixi-framework/libtrixi#125]
The following error was reported by @bgeihe when running an executable linked against a PackageCompiler-compiled libtrixi:
```
*** Trixi controller ***  Initialize Trixi 
trixi_initialize: 'project_directory' is non-null but will not be used 
fatal: error thrown and no exception handler available. 
InitError(mod=:Trixi, error=ErrorException("could not load library "/home/user/install/t8code/lib/libt8.so" 
/home/user/libtrixi/LibTrixi.jl/lib/build/lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/user/install/t8code/lib/libt8.so)"))
```
It seems like the local installation of t8code was built against a newer version of libstdc++ (`/usr/lib/libstdc++.so.6.0.32`) that expects `GLIBCXX_3.4.32` , while Julia's own libstdc++ (`libstdc++.so.6.0.30`) only provides an older variant.

The problem could be remedied by preloading the system libstdc++, i.e., by calling the executable with
```shell
LD_PRELOAD=/usr/lib/libstdc++.so.6 ./simple_trixi_controller_c ...
```

This seems like an issue that a) could come up at other systems as well and b) that is super annoying to solve for the users. It would therefore be great if we found a solution to
a) detect this issue during the build
b) fix this issue automatically during the build

**Comment by sloede** [comment]
xref https://discourse.julialang.org/t/precedence-of-local-and-julia-shipped-shared-libraries/104258

**Comment by sloede** [comment]
@bgeihe Can you please try to install PackageCompiler.jl from this branch
https://github.com/sloede/PackageCompiler.jl/tree/msl/bundle-dynamically-selected-libstdc%2B%2B
and see if it fixes the problem?

With this version of PC.jl, on your system with the newer version `/usr/lib/libstdc++.so.6.0.32` you should end up with a `build/lib/julia` directory that contains the following `libstdc++` names:
```
build/lib/julia/libstdc++.so -> libstdc++.so.6.0.32
build/lib/julia/libstdc++.so.6 -> libstdc++.so.6.0.32
build/lib/julia/libstdc++.so.6.0.32
```
while before you ended up with

```
build/lib/julia/libstdc++.so -> libstdc++.so.6.0.30
build/lib/julia/libstdc++.so.6 -> libstdc++.so.6.0.30
build/lib/julia/libstdc++.so.6.0.30
```
Of course, the true test would then be if you can run your programs linked against `libtrixi.so` __without__ having to specify `LD_PRELOAD` anymore.

**Comment by bgeihe** [comment]
It works!

PackageCompiler picks up the right version
>  │    ├── libstdc++.so.6.0.32 - 20.516 MiB

The right library ends up in 
> ../LibTrixi.jl/lib/build/lib/julia/libstdc++.so.6.0.32

And `simple_trixi_controller_c` successfully without `LD_PRELOAD`.

Awesome!

**Comment by sloede** [comment]
Awesome 👍 And thanks for verifying so quickly!

Can you also confirm that `PREFIX/lib/julia` contains the right symlinks as stated above?

Maybe you can add the confirmation that it works as expected yourself as a reply to https://github.com/JuliaLang/PackageCompiler.jl/pull/853#discussion_r1341936041. Otherwise, I can also let them know.

**Comment by bgeihe** [comment]
Yep! Symlinks are correct as well!

**Comment by sloede** [comment]
If this issue has been resolved for you @bgeihe, could you please let me know and/or close the issue?

**Comment by bgeihe** [comment]
All good!
