### ISSUE TITLE
No overview of Fortran API?

### ISSUE THREAD

**Issue by sloede** [trixi-framework/libtrixi#130]
When going to the docs, there does not seem to be a link anymore to browse the Fortran API. Has this been removed or was it just never there? And, more importantly, can we get it back?
<img width="840" alt="image" src="https://github.com/trixi-framework/libtrixi/assets/3637659/d646334d-2138-462a-a0b8-32b0023aff94">

**Comment by bgeihe** [comment]
Even worse, the C documentation is botched: no brief or detailed description, parameter documentation, ...

It seem as if only `trixi.h` is taken into account.

**Comment by sloede** [comment]
Ah, I believe this line might be the source of all (some) evil:
https://github.com/trixi-framework/libtrixi/blob/f448c066a97c2f4a9f55e239feba319479154dcf/docs/doxygen/Doxyfile#L946

**Comment by sloede** [comment]
see #131 for an attempt to remedy this
