### ISSUE TITLE
Precompiling LibTixi.jl fails on main

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#135]
Since last week the setup of the Julia project fails, also on main.

The error message is attached but not very instructive. 
> *** An error occurred in MPI_Init_thread
[ci_fail.txt](https://github.com/trixi-framework/libtrixi/files/12844124/ci_fail.txt)

Comparing to the last successful CI run for main, the differences in Julia packages are:

```
35c34
< ⌅ [fa961155] + CEnum v0.4.2
---
>   [fa961155] + CEnum v0.4.2
56c55
<   [6b5a15aa] + P4est_jll v2.8.1+3
---
>   [6b5a15aa] + P4est_jll v2.8.1+2
159c152
<   [b4f34e82] + Distances v0.10.10
---
>   [b4f34e82] + Distances v0.10.9
194c187
<   [7ed4a6bd] + LinearSolve v2.9.2
---
>   [7ed4a6bd] + LinearSolve v2.8.1
206c199
<   [8913a72c] + NonlinearSolve v2.1.0
---
>   [8913a72c] + NonlinearSolve v2.0.1
210c203
<   [1dea7af3] + OrdinaryDiffEq v6.58.0
---
>   [1dea7af3] + OrdinaryDiffEq v6.57.0
233c226
<   [47a9eef4] + SparseDiffTools v2.7.0
---
>   [47a9eef4] + SparseDiffTools v2.6.0
292c286
<   [1dea7af3] + OrdinaryDiffEq v6.58.0
---
>   [1dea7af3] + OrdinaryDiffEq v6.57.0
```

So, this could be related to
https://github.com/trixi-framework/P4est.jl/pull/88/files
see the discussion
https://github.com/trixi-framework/P4est.jl/pull/88

The issue can be reproduced on rocinante. (precompilation step of the `libtrixi-julia` project)

It works on my local machine.

**Comment by bgeihe** [comment]
Related #134

**Comment by JoshuaLampert** [comment]
It's very likely that this is caused by https://github.com/JuliaPackaging/Yggdrasil/pull/7500 and should be fixed with https://github.com/JuliaPackaging/Yggdrasil/pull/7510. I had the same error message locally because of the changes from https://github.com/JuliaPackaging/Yggdrasil/pull/7500.

**Comment by bgeihe** [comment]
Thanks @JoshuaLampert for the hints and the hot fix.

I would be interested in finding the root cause, as we had a similar issue reported by one of the libtrixi users (which however might also be unrelated).

Note that is works on my local machine. So maybe it has something to do with different versions? (e.g. openmpi 4.0.3 on rocinante, 4.1.5 here)

**Comment by JoshuaLampert** [comment]
That's interesting. Do you observe different behavior than I have reported in https://github.com/trixi-framework/P4est.jl/pull/88#issuecomment-1751660852 on your machine? Or does it still use the OpenMPI version from the artifact, but it does not lead to an error in your case?
 I am also interesting in finding the root cause and am planning to invest some time to find it (not exactly sure when I find time though). If you are willing to help, I would be happy and we can coordinate efforts.

**Comment by sloede** [comment]
@bgeihe can we close this?

**Comment by bgeihe** [comment]
Well, it is currently fixed, so we do not need to keep it open, at least not here.
