### ISSUE TITLE
Check using JULIA_DEFINE_FAST_TLS

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#22]
If this really makes a performance difference, we might have to compile libtrixi as a static library, i.e., `libtrixi.a`.

_Originally posted by @sloede in https://github.com/trixi-framework/libtrixi/pull/20#discussion_r1238720120_

**Comment by sloede** [comment]
See also (hopefully 🤞) https://discourse.julialang.org/t/effect-of-julia-define-fast-tls-and-how-to-handle-in-shared-library-or-fortran/101114
