### ISSUE TITLE
Document MPI setup

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#26]
This is not complete yet, e.g. switching to system MPI and p4est. 

_Originally posted by @bgeihe in https://github.com/trixi-framework/libtrixi/issues/10#issuecomment-1602942752_

**Comment by sloede** [comment]
I think once #24 has been merged to `main`, fixing this issue here should be relatively straightforward, since most of the heavy lifting is done by the `libtrixi-init-julia` script

**Comment by bgeihe** [comment]
Yeah, `libtrixi-init-julia` does the trick. #20 explains the usage.
