### ISSUE TITLE
invokelatest not exported for julia 1.8

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#38]
When using `julia` version 1.8 the following error occurs:
```
[...]
UndefVarError(var=:invokelatest)
[...]
```
Do we need to replace `invokelatest` by `Base.invokelatest`?

**Comment by sloede** [comment]
Yes, please create a PR! I forgot about it (https://github.com/JuliaLang/julia/blob/v1.9.0/NEWS.md#language-changes).
