### ISSUE TITLE
Provide an example on how to use libtrixi

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#4]
Should we somewhere add an example `CMakeLists.txt` which compiles the `fortran_hello_world` as a standalone cmake project? Or maybe just add the cmake code to `README.md`?

For reference:
```
#
# Fortran Hello Trixi
#



# Specify minimum cmake version
cmake_minimum_required ( VERSION 3.0 )

# Specify project info
project ( fortran_hello_world VERSION 0.1.0 DESCRIPTION "Example for using libtrixi Fortran" )

# Enable Fortran
enable_language(Fortran)



# Find libtrixi
find_library ( TRIXI_LIBRARY trixi REQUIRED)

# Find libtrixi.mod
find_path ( TRIXI_MOD_DIR libtrixi.mod PATH_SUFFIXES lib REQUIRED)

# Find MPI
find_package( MPI REQUIRED )

# Find Julia
list ( APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}" )
find_package( Julia REQUIRED )



# Define the executable
add_executable(${PROJECT_NAME} fortran_hello_world.f90)

# Add libraries for linking
target_link_libraries(${PROJECT_NAME} PRIVATE ${MPI_Fortran_LIBRARIES} ${TRIXI_LIBRARY} ${JULIA_LIBRARY})

# Add include directories
target_include_directories(${PROJECT_NAME} PRIVATE ${MPI_Fortran_INCLUDE_DIRS} ${TRIXI_MOD_DIR})
```

Requires `CMAKE_PREFIX_PATH=<libtrixi_install_directory>` when running cmake.

_Originally posted by @bgeihe in https://github.com/trixi-framework/libtrixi/issues/1#issuecomment-1591086591_

**Comment by sloede** [comment]
Personally, I would not put it in the README - too much clutter. Instead, I would maybe just put the standalone `CMakeLists.txt` inside the `examples/` folder and then add a section to the README such as "Building the examples", which explains how to build the examples after having built the library itself. That way, the user has an easy enough time to get started, but also sees all code that is relevant for hooking up their own program with libtrixi.

**Comment by sloede** [comment]
Also, IMHO we should always have a C (and/or C++) based example, that mimics the Fortran example. C/C++ are just far better understood by the majority of users (I believe), and it might help for debugging when we want to rule out some issues and don't know if it is due to some weird Fortran <--> C conversion or something else.
