### ISSUE TITLE
Add `trixi_version_julia` to provide info on Julia package versions

### ISSUE THREAD

**Issue by sloede** [trixi-framework/libtrixi#66]
Right now, `trixi_version` prints out the version of libtrixi, e.g., `0.1.0-dev`. I think it would be helpful for debugging purposes if we had an API function `trixi_version_julia` that outputs additional information about the underlying Julia packages currently used and Julia itself, e.g., something like this:
```
LibTrixi v0.1.0-pre
Trixi v0.5.34
OrdinaryDiffEq v5.26.3
julia v1.9.1
```

This could then also be automatically shown if `LIBTRIXI_DEBUG` is enabled.

**Comment by bgeihe** [comment]
Sounds good!

I assume there is some nice juliaish way to accomplish this? Using `Pkg`? I would happily figure this out, unless you already know how to do it.

**Comment by sloede** [comment]
> I assume there is some nice juliaish way to accomplish this? Using `Pkg`? I would happily figure this out, unless you already know how to do it.

Unfortunately, I don't. Getting the Julia version is trivial, but getting specific package versions from `Pkg` is not doable in a very elegant way, IIRC. But it would be great if you can take a stab at this.

**Comment by bgeihe** [comment]
1. Currently we output the status of the julia project
  ```
  [f67ccb44] HDF5 v0.16.15
  [7e097bd5] LibTrixi v0.1.0 `../libtrixi_main/share/libtrixi/LibTrixi.jl`
  [da04e1cc] MPI v0.20.13
  [3da0fdf6] MPIPreferences v0.1.9
  [1dea7af3] OrdinaryDiffEq v6.53.4
  [7d669430] P4est v0.4.7
  [21216c6a] Preferences v1.4.0
  [d0cc0030] T8code v0.4.1
  [a7f1ee26] Trixi v0.5.37
  [cf7118a7] UUIDs
  ```
  I assume this is not sufficient as we are not able to access the actual data, but can merely print it?

2. Something like this seems to work
  ```
  julia> using Pkg
  julia> pkg_manifest = Pkg.Operations.Context().env.manifest
  julia> pkg_manifest[findfirst(v -> v.name == "Trixi", pkg_manifest)]
  PackageEntry(
    name = Trixi
    version = 0.5.37
    tree_hash = 31fa40be33d1189add1eab34547b745dbd2ebb17
  )
  ```
It would allow to query the version of any package, given by its name, recorded in the manifest.

**Comment by sloede** [comment]
> I assume this is not sufficient as we are not able to access the actual data, but can merely print it?

Yes, what I don't like about it is also that it is not easily parseable since there is more information available than just `NAME VERSION` in each line.

If we'd be happy with a list of packages sorted by name, we could also do something like the following:
```julia
using Pkg

packages = Pkg.dependencies() |> values |> collect |> filter(p -> p.is_direct_dep)

versions = String[]
for p in sort(packages, by=x->x.name)
  push!(versions, p.name * " " * string(p.version))
end
push!(versions, "julia " * string(VERSION))

println(join(versions, "\n"))
```
which prints something like
```
OrdinaryDiffEq 6.52.0
Trixi 0.5.27-pre
julia 1.9.1
```

In this case we could easily implement also a `trixi_version_julia_extended` function that shows the package version for all packages, by omitting the `filter(...)` part.

**Comment by bgeihe** [comment]
This already looks pretty sophisticated! 

When I looked at Pkg.dependencies(), I apparently missed the dots at the end of the screen and did not realize the actual size of the dict...

Anyway, what about the second idea? Would it ease the implementation? Admittedly, your proposal already is very concise and I would be happy with it.

**Comment by sloede** [comment]
`Pkg.dependencies()` is also not perfect, since it is marked as "experimental" in the docs. However, it seems like the "cleanest of the unclean" options we have (at least it is documented at all!).

Do you want to take a stab at implementing this?

One issue still to be decided would be how to return the string to the user. The easiest from an API implementer's POV is to have something like
```julia
trixi_version_julia()::Cstring
```
which will return a pointer to a string. However, this method is somewhat volatile, as the pointer is only guaranteed to be valid until the next call to a Julia function, and it is thus, by extension, also inherently not thread-safe.

The alternative would be to implement something akin to the [`snprintf`](https://en.cppreference.com/w/c/io/fprintf) API, i.e.,
```julia
trixi_version_julia(buffer::Ptr{Cchar}, buffer_size::Cint)::Cint
```
which accepts a pointer `buffer` to `char*` to which the version information should be written, a maximum length `buffer_size` to avoid overflow, and which returns the number of bytes that would have been written if `buffer_size` had been ignored. By setting `buffer_size` to zero it also be used to query the length of the returned string, i.e., allowing something like
```c
int buffer_size = trixi_version_julia(NULL, 0);
char buffer[buffer_size + 1]; // +1 for the terminating null byte
trixi_version_julia(buffer, buffer_size + 1); // +1 for the terminating null byte
```

The former is easier to implement from our side, but the latter is definitely the safer version since it does not rely as much on the user doing "the right thing" and not using this in an unsafe way. In case we use the latter, we should probably also implement a second version in LibTrixi.jl tha returns a plain Julia string, i.e.,
```julia
trixi_version_julia()::String
```
such that it is more convenient to use for testing.

Finally, we could also just go with your original proposal and have it write all information to `stdout`. However, the ability to store this as a string is nice if it is to be included, e.g., in some log files etc.

**Comment by bgeihe** [comment]
> Do you want to take a stab at implementing this?

Definitely!


But what do you think of the second approach?
```
julia> using Pkg
julia> pkg_manifest = Pkg.Operations.Context().env.manifest
julia> pkg_manifest[findfirst(v -> v.name == "Trixi", pkg_manifest)]
PackageEntry(
  name = Trixi
  version = 0.5.37
  tree_hash = 31fa40be33d1189add1eab34547b745dbd2ebb17
)
```
Are there any pros or cons?

**Comment by sloede** [comment]
The main downside I see is that the approach lies - AFAICT - on undocumented implementation details of the Pkg.jl package. While [`Pkg.dependencies`](https://pkgdocs.julialang.org/v1/api/#Pkg.dependencies) is marked as experimental, it is at least part of the publicly documented API.

Other than that, I think the approaches are nearly identical and I assume that Pkg.dependencies internally makes use of the Context information.

**Comment by bgeihe** [comment]
I see. Thanks for explaining!

**Comment by bgeihe** [comment]
Trying to get this straight.

1. Using your `Pkg.dependencies()` snippet we get a sorted name / version dict. Do we want two of those? One for `p.is_direct_dep` and one without? Or could we add a corresponding flag to our dictionary?
 2. We query this dict via julia functions `trixi_version_julia` and `trixi_version_julia_extended`, or also per package, i.e. something like `trixi_version_julia(packageName)`?
 3. (referring to slack) We create interface functions returning `ptr(string)`, i.e. `@ccallable fun()::ptr(string)`?
 4. We need to copy the returned string on the C-side to avoid it being freed by GC?
 5. We then use the `snprintf` like approach to return it to our user? Or just return a `char*` , which has to be freed somehow at the end?

**Comment by sloede** [comment]
> Trying to get this straight.
> 
>     1. Using your `Pkg.dependencies()` snippet we get a sorted name / version dict. Do we want two of those? One for `p.is_direct_dep` and one without? Or could we add a corresponding flag to our dictionary?

Regular Julia `Dict`s are never sorted. In my snippet, `packages` is already a `Vector`. The `is_direct_dep` is used to obtain only those packages which are directly added to the `Project.toml`, and to skip their dependencies. That should usually be sufficient information. The `_extended` version could then show the versions of all packages (i.e., also from recursive dependencies).

> 
>     2. We query this dict via julia functions `trixi_version_julia` and `trixi_version_julia_extended`, or also per package, i.e. something like `trixi_version_julia(packageName)`?

Since this is mainly useful for debugging, I think we should go for least effort and just show everything. A per-package version I'd only add if specifically required by someone.

> 
>     3. (referring to slack) We create interface functions returning `ptr(string)`, i.e. `@ccallable fun()::ptr(string)`?

If we implement `trixi_version_julia(buffer::Ptr{Cchar}, buffer_size::Cint)::Cint`, there's no need for a function `fun()::Cstring` anymore.

> 
>     4. We need to copy the returned string on the C-side to avoid it being freed by GC?

If we use `trixi_version_julia(buffer::Ptr{Cchar}, buffer_size::Cint)::Cint`, there's no need for this anymore, since this function already copies the string to memory managed by C.

> 
>     5. We then use the `snprintf` like approach to return it to our user?

Yes.

> Or just return a `char*` , which has to be freed somehow at the end?

No, I would strongly recommend to not have memory allocated in one part and then freed in another part. IMHO, that's a recipe for disaster 😬

**Comment by sloede** [comment]
There's another approach we could follow, one that would make the C/Fortran interface essentially just as easy to use as for the existing `trixi_version_xxx` functions. In LibTrixi.jl, we could add global variables to hold the version info and initialize them in the `__init__` function of LibTrixi.jl to the correct strings with the relevant version information, e.g.,
```julia
const _version_info = Ref("")
const _version_info_extended = Ref("")

function __init__()
    ...

    _version_info[] = begin
        packages = Pkg.dependencies() |> values |> collect |> filter(p -> p.is_direct_dep)

        versions = String[]
        for p in sort(packages, by=x->x.name)
            push!(versions, p.name * " " * string(p.version))
        end
        push!(versions, "julia " * string(VERSION))

        join(versions, "\n")
    end

    _version_info_extended[] = ...
end
```

Then, on the Julia side we implement the version functions by just returning a pointer to the respective variables, e.g.,
```julia
@ccallable function trixi_version_julia()::Cstring
    return pointer(_version_info)
end
```

This would return a pointer to a null-terminated C string, similar to `trixi_version_xxx`. If these `trixi_version_julia()` functions are called on the C side before `trixi_initialize`, it would be undefined behavior, but that's OK imho, since before Julia is initialized, all Julia calls are UB. The nice thing here is that the pointer is guaranteed to remain the same throughout the lifetime of the program.

**Comment by bgeihe** [comment]
Yeah!

**Comment by bgeihe** [comment]
Should we now extract LibTrixi's version to address
https://github.com/trixi-framework/libtrixi/issues/62#issuecomment-1663965408?

**Comment by sloede** [comment]
Yep, makes sense!
