### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#74]
Mother issue for testing.

Goals:

- [x] #73
- [x] #82 
- [x] #67
- [x] #85 
- [x] #49

**Comment by sloede** [comment]
Great idea to create this meta issue! I slightly re-formatted your post (hope that it's ok) such that completed issues get checked off automatically.

**Comment by sloede** [comment]
With #85 having been merged, this can be closed IMHO (feel free to reopen if you disagree).
