### ISSUE TITLE
Parallel simulation of libelixir_p4est2d_dgsem_euler_sedov.jl hangs (?)

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#83]
Command line:
```
LIBTRIXI_DEBUG=all mpirun -n 2 ./bin/simple_trixi_controller_c ../libtrixi-julia ./share/libtrixi/LibTrixi.jl/examples/libelixir_p4est2d_dgsem_euler_sedov.jl
```
After initialization and 
```
Simulation running 'CompressibleEulerEquations2D' with DGSEM(polydeg=4)
[...]
```

there is no progress anymore. Both processes use 100% CPU.

`libelixir_tree2d_dgsem_euler.jl` still works as expected.

**Comment by sloede** [comment]
Can you reproduce by using Julia only, i.e., by directly using LibTrixi.jl?

**Comment by bgeihe** [comment]
Yes, indeed!

- It fails when using `LibTrixi.jl`
- It also fails when using julia with the libtrixi-julia project and then doing ` mpiexec() [...] using Trixi; trixi_include(...) [...]
- It works when using the official Trixi.jl package in a clean julia project

So this has something to do with system MPI, I assume.

When frozen, Ctrl+C gives:
> [10950] signal (15): Terminated
> in expression starting at /home/bene/libtrixi_main/examples/simple_trixi_controller.jl:8
> unknown function (ip: 0x7f3055c91769)
> progress_one_cuda_ipc_event at /usr/lib/libmca_common_cuda.so.40 (unknown line)
> mca_btl_smcuda_component_progress at /usr/lib/openmpi/mca_btl_smcuda.so (unknown line)
> opal_progress at /usr/lib/libopen-pal.so.40 (unknown line)
> ompi_sync_wait_mt at /usr/lib/libopen-pal.so.40 (unknown line)
> ompi_request_default_wait at /usr/bin/../lib/julia/../libmpi.so (unknown line)
> ompi_coll_base_barrier_intra_recursivedoubling at /usr/bin/../lib/julia/../libmpi.so (unknown line)
> mca_sharedfp_sm_file_open at /usr/lib/openmpi/mca_sharedfp_sm.so (unknown line)
> unknown function (ip: 0x7f2fe481bd11)
> mca_io_ompio_file_open at /usr/lib/openmpi/mca_io_ompio.so (unknown line)
> mca_io_base_file_select at /usr/bin/../lib/julia/../libmpi.so (unknown line)
> ompi_file_open at /usr/bin/../lib/julia/../libmpi.so (unknown line)
> MPI_File_open at /usr/bin/../lib/julia/../libmpi.so (unknown line)
> p4est_save_ext at /home/bene/t8code_build_fortran/p4est/../../t8code/p4est/src/p4est.c:3605
> p4est_save at /home/bene/t8code_build_fortran/p4est/../../t8code/p4est/src/p4est.c:3463
> p4est_save at /home/bene/install/libtrixi-julia/julia-depot/packages/P4est/PSrSX/src/LibP4est.jl:4682
> save_p4est! at /home/bene/install/libtrixi-julia/julia-depot/packages/Trixi/vuHm4/src/auxiliary/p4est.jl:82 [inlined]
> save_mesh_file at /home/bene/install/libtrixi-julia/julia-depot/packages/Trixi/vuHm4/src/meshes/mesh_io.jl:199
> [...]

As `libmca_common_cuda` came up, I tried running with `OMPI_MCA_mpi_cuda_support=0`, which brought me to the first `save_solution` callback, but got then stuck at this point. Ctrl+C then gives

> [11901] signal (15): Terminated
> in expression starting at /home/bene/libtrixi_main/examples/simple_trixi_controller.jl:14
> opal_progress at /usr/lib/libopen-pal.so.40 (unknown line)
> ompi_sync_wait_mt at /usr/lib/libopen-pal.so.40 (unknown line)
> ompi_request_default_wait at /usr/bin/../lib/julia/../libmpi.so (unknown line)
> ompi_coll_base_barrier_intra_recursivedoubling at /usr/bin/../lib/julia/../libmpi.so (unknown line)
> mca_sharedfp_sm_file_open at /usr/lib/openmpi/mca_sharedfp_sm.so (unknown line)
> unknown function (ip: 0x7f8fcc6c9d11)
> mca_io_ompio_file_open at /usr/lib/openmpi/mca_io_ompio.so (unknown line)
> mca_io_base_file_select at /usr/bin/../lib/julia/../libmpi.so (unknown line)
> ompi_file_open at /usr/bin/../lib/julia/../libmpi.so (unknown line)
> MPI_File_open at /usr/bin/../lib/julia/../libmpi.so (unknown line)
> H5FD__mpio_open at /home/bene/install/libtrixi-julia/julia-depot/artifacts/ce5ad50f2442fd6f95f2f60aed308dffe10751c6/lib/libhdf5.so (unknown line)
> H5FD_open at /home/bene/install/libtrixi-julia/julia-depot/artifacts/ce5ad50f2442fd6f95f2f60aed308dffe10751c6/lib/libhdf5.so (unknown line)
> H5F_open at /home/bene/install/libtrixi-julia/julia-depot/artifacts/ce5ad50f2442fd6f95f2f60aed308dffe10751c6/lib/libhdf5.so (unknown line)
> H5VL__native_file_create at /home/bene/install/libtrixi-julia/julia-depot/artifacts/ce5ad50f2442fd6f95f2f60aed308dffe10751c6/lib/libhdf5.so (unknown line)
> H5VL_file_create at /home/bene/install/libtrixi-julia/julia-depot/artifacts/ce5ad50f2442fd6f95f2f60aed308dffe10751c6/lib/libhdf5.so (unknown line)
> H5F__create_api_common at /home/bene/install/libtrixi-julia/julia-depot/artifacts/ce5ad50f2442fd6f95f2f60aed308dffe10751c6/lib/libhdf5.so (unknown line)
> H5Fcreate at /home/bene/install/libtrixi-julia/julia-depot/artifacts/ce5ad50f2442fd6f95f2f60aed308dffe10751c6/lib/libhdf5.so (unknown line)
> h5f_create at /home/bene/install/libtrixi-julia/julia-depot/packages/HDF5/MIuzl/src/api/functions.jl:1084
> #h5open#14 at /home/bene/install/libtrixi-julia/julia-depot/packages/HDF5/MIuzl/src/file.jl:43
> h5open at /home/bene/install/libtrixi-julia/julia-depot/packages/HDF5/MIuzl/src/file.jl:20 [inlined]
> #h5open#15 at /home/bene/install/libtrixi-julia/julia-depot/packages/HDF5/MIuzl/src/file.jl:72
> h5open at /home/bene/install/libtrixi-julia/julia-depot/packages/HDF5/MIuzl/src/file.jl:60
> #h5open#19 at /home/bene/install/libtrixi-julia/julia-depot/packages/HDF5/MIuzl/src/drivers/mpio.jl:112 [inlined]
> h5open at /home/bene/install/libtrixi-julia/julia-depot/packages/HDF5/MIuzl/src/drivers/mpio.jl:105 [inlined]
> h5open at /home/bene/install/libtrixi-julia/julia-depot/packages/HDF5/MIuzl/src/drivers/mpio.jl:105 [inlined]
> #h5open#16 at /home/bene/install/libtrixi-julia/julia-depot/packages/HDF5/MIuzl/src/file.jl:92 [inlined]
> h5open at /home/bene/install/libtrixi-julia/julia-depot/packages/HDF5/MIuzl/src/file.jl:91 [inlined]
> save_solution_file_parallel at /home/bene/install/libtrixi-julia/julia-depot/packages/Trixi/vuHm4/src/callbacks_step/save_solution_dg.jl:142

**Comment by sloede** [comment]
This occurs in Roci? What happens if you disable the save solution cb?

**Comment by bgeihe** [comment]
Just an update: It works on rocinante! I hope it will also do so in our CI, but this will eventually be tested.
