### ISSUE TITLE
Failing `trixi_initialize()` when called again after `trixi_finalize()`

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#88]
When doing something like
```
trixi_initialize( project_path, NULL );
[...]
trixi_finalize();
trixi_initialize( project_path, NULL );
```
we get
```
libtrixi: finalize
ERROR in /home/bene/libtrixi/src/api.c:95 (trixi_initialize):
The following Julia code could not be evaluated: println("Module LibTrixi.jl loaded")
```
i.e. after `trixi_finalize()`, and thereby `jl_atexit_hook(0)`, and the following `trixi_initialize()`, and thereby `jl_init()`, the subsequent calls to `jl_eval_string` fail. To be precise, the first call with `using Pkg` does not fail (but maybe does not work correctly either?), but the following call with `Pkg.activate(...)` fails. (Normally it is not visible in console output, so the first visible failure is the call with `println(...)`.

**Comment by sloede** [comment]
I agree. This is an annoying error with a very non-helpful error message. I recommend the following solution:

Add a new variable to `src/api.c`,
```c
static int is_initialized = 0;
static int is_finalized = 0;
```
then, set the variables appropriately in `trixi_initialize`/`trixi_finalize`.
Finally, handle the following cases with a helpful error message:
* call to `trixi_initialize` if `is_initialized`
* call to `trixi_initialize` if `is_finalized`
* call to `trixi_finalize` if `!is_initialized`
* call to `trixi_finalize` if `is_finalized`

**Comment by bgeihe** [comment]
Good idea. This would be a clean way!

My main concern was that I did not expect 

- call to `trixi_initialize` if `is_finalized`

to fail. I do not understand what goes wrong, but I at least wanted to write it down somewhere.

Anyway, catching those case is even better.

**Comment by bgeihe** [comment]
Even more strange: In the latest CI run of #89, the first `initialize`/`finalize` works, the second fails, and the third works again.

**Comment by sloede** [comment]
I would not bother trying to understand this further. It is very well possible that the calls to `jl_init` and `jl_atexit_hook` cannot be called multiple times, thus I'd assume it is not allowed and therefore we should safeguard against it.
