### ISSUE TITLE
Store C function pointers from LibTrixi.jl inside libtrixi

### ISSUE THREAD

**Issue by sloede** [trixi-framework/libtrixi#9]
Motivated by a separation of concerns and - possibly - by performance considerations, we should store the C function pointers inside libtrixi instead of getting them each time with a call to `jl_eval_string("some_function_cfptr()")`. Ideally, we'd only have calls to low-level libjulia functions in `trixi_initialize` and `trixi_finalize`, while all others functions directly call into LibTrixi.jl using C function pointers.

**Comment by bgeihe** [comment]
1. Except for `trixi_initialize` and `trixi_finalize`, all functions in libtrixi follow the same pattern. This could be auto-generated or replaced by macros, except for the parameters and returns. But this does not help with possible performance issues.

2. An array of function pointers is not trivial as the signatures differ.

**Comment by sloede** [comment]
I think that shouldn't be too hard to fix: function pointers are just regular pointers with additional, syntactic meaning. That means they can just be stored inside an array of `void *`, and then casted back to the appropriate function pointer at the callsite. I am thinking about something like 
```c
// Inside the library's main scope
static void* trixi_fptrs[2];
enum TRIXI_FPTRS {TRIXI_FPTR_CALCULATE_DT, TRIXI_FPTR_STEP};

// Inside trixi_initialize(...)
trixi_ftprs[TRIXI_FPTR_CALCULATE_DT] = (void *)jl_unbox_voidpointer( checked_eval_string("trixi_calculate_dt_cfptr()", LOC) ) ;

// Inside trixi_calculate_dt(...)
double (*trixi_calculate_dt_c)(int) = trixi_ftprs[TRIXI_FPTR_CALCULATE_DT];
```
That way, we do not have to suffer the overhead of calling `jl_eval_string` each time...
