### ISSUE TITLE
Set C and Fortran standard versions 

### ISSUE THREAD

**Issue by sloede** [trixi-framework/libtrixi#90]
We should explicitly set the C/Fortran versions we want to compile against such that there are no surprises about features being supported differently on different compilers, or ambiguity about which features we use or need.

Since requiring an arbitrarily recent language standard limits the choice of compilers, I suggest to try to play it safe for now and require C11 and Fortran ~~2008~~ 2018 (if those actually work).

**EDIT**: We actually need Fortran 2018 😱

**Comment by bgeihe** [comment]
Sounds good!

A corresponding cmake feature is missing for Fortran
https://gitlab.kitware.com/cmake/cmake/-/issues/25006
but of course we can specifiy `-std=` manually.

**Comment by bgeihe** [comment]
> EDIT: We actually need Fortran 2018 😱
Oh! How come? Do we need to alleviate this?

**Comment by sloede** [comment]
> > EDIT: We actually need Fortran 2018 😱
> 
> Oh! How come? Do we need to alleviate this?

```
/home/mschlott/hackathon/libtrixi/src/api.f90:33:63:

   33 |     subroutine trixi_initialize_c(project_directory, depot_path) bind(c, name='trixi_initialize')
      |                                                               1
Error: Fortran 2018: Variable ‘depot_path’ at (1) with OPTIONAL attribute in procedure ‘trixi_initialize_c’ which is BIND(C)
```
Because we allow to omit the second argument (such that it is implicitly passed as a null pointer). I don't think we need to do anything right now unless users complain 🤞

**Comment by bgeihe** [comment]
Yeah! :crossed_fingers:
